export const LANGUAGE = {
  // English
  'en': {
    // Angles
    'ascendant': 'Ascendant',
    'midheaven': 'Midheaven',
    // Bodies
    'sun': 'Sun',
    'moon': 'Moon',
    'mercury': 'Mercury',
    'venus': 'Venus',
    'mars': 'Mars',
    'jupiter': 'Jupiter',
    'saturn': 'Saturn',
    'uranus': 'Uranus',
    'neptune': 'Neptune',
    'pluto': 'Pluto',
    'chiron': 'Chiron',
    'sirius': 'Sirius',
    // Points
    'northnode': 'North Node',
    'southnode': 'South Node',
    'lilith': 'Lilith',
    // Signs
    'aries': 'Aries',
    'taurus': 'Taurus',
    'gemini': 'Gemini',
    'cancer': 'Cancer',
    'leo': 'Leo',
    'virgo': 'Virgo',
    'libra': 'Libra',
    'scorpio': 'Scorpio',
    'sagittarius': 'Sagittarius',
    'capricorn': 'Capricorn',
    'aquarius': 'Aquarius',
    'pisces': 'Pisces',
    'ophiuchus': 'Ophiuchus',
    // Houses
    'house1': 'First',
    'house2': 'Second',
    'house3': 'Third',
    'house4': 'Fourth',
    'house5': 'Fifth',
    'house6': 'Sixth',
    'house7': 'Seventh',
    'house8': 'Eigth',
    'house9': 'Ninth',
    'house10': 'Tenth',
    'house11': 'Eleventh',
    'house12': 'Twelfth',
    // Aspects
    'conjunction': 'Conjunction',
    'opposition': 'Opposition',
    'trine': 'Trine',
    'square': 'Square',
    'sextile': 'Sextile',
    'quincunx': 'Quincunx',
    'quintile': 'Quintile',
    'septile': 'Septile',
    'semi-square': 'Semi-Square',
    'semi-sextile': 'Semi-Sextile',
    // Language labels
    'en': 'English',
    'es': 'Español',
    // Zodiac Choice Labels
    'tropical-zodiac': 'Tropical',
    'sidereal-zodiac': 'Sidereal',
    // House System labels
    'equal-house': 'Equal House',
    'koch': 'Koch',
    'placidus': 'Placidus',
    'regiomontanus': 'Regiomontanus',
    'topocentric': 'Topocentric',
    'whole-sign': 'Whole Sign',
    // Aspect level labels
    'major': 'Major',
    'minor': 'Minor',
  },
  // Spanish
  es: {
    // Angles
    'ascendant': 'Ascendente',
    'midheaven': 'Medio Cielo',
    // Bodies
    'sun': 'Sol',
    'moon': 'Luna',
    'mercury': 'Mercurio',
    'venus': 'Venus',
    'mars': 'Marte',
    'jupiter': 'Júpiter',
    'saturn': 'Saturno',
    'uranus': 'Urano',
    'neptune': 'Neptuno',
    'pluto': 'Plutón',
    'chiron': 'Quirón',
    'sirius': 'Sirio',
    // Points
    'northnode': 'Nodo Norte',
    'southnode': 'Nodo Sur',
    'lilith': 'Lilith',
    // Signs
    'aries': 'Aries',
    'taurus': 'Tauro',
    'gemini': 'Géminis',
    'cancer': 'Cáncer',
    'leo': 'Leo',
    'virgo': 'Virgo',
    'libra': 'Libra',
    'scorpio': 'Escorpio',
    'sagittarius': 'Sagitario',
    'capricorn': 'Capricornio',
    'aquarius': 'Acuario',
    'pisces': 'Piscis',
    'ophiuchus': 'Ofiuco',
    // Houses
    'house1': 'Primera',
    'house2': 'Segunda',
    'house3': 'Tercera',
    'house4': 'Cuarta',
    'house5': 'Quinta',
    'house6': 'Sexta',
    'house7': 'Séptima',
    'house8': 'Octava',
    'house9': 'Novena',
    'house10': 'Décima',
    'house11': 'Undécima',
    'house12': 'Duodécima',
    // Aspects
    'conjunction': 'Conjunción',
    'opposition': 'Oposición',
    'trine': 'Trígono',
    'square': 'Cuadrado',
    'sextile': 'Sextil',
    'quincunx': 'Tresbolillo',
    'quintile': 'Quintil',
    'septile': 'Septil',
    'semi-square': 'Semi-cuadrado',
    'semi-sextile': 'Semi-sextil',
    // Language labels
    'en': 'English',
    'es': 'Español',
    // Zodiac Choice Labels
    'tropical-zodiac': 'Tropical',
    'sidereal-zodiac': 'Sideral',
    // House System labels
    'equal-house': 'Casa igual',
    'koch': 'Koch',
    'placidus': 'Placidus',
    'regiomontanus': 'Regiomontanus',
    'topocentric': 'Topocéntrico',
    'whole-sign': 'Signo Entero',
    // Aspect level labels
    'major': 'Mayor',
    'minor': 'Menor',
  }
}
