export const LANGUAGE = {
  'en': {
    // Angles
    'ascendant': 'Ascendant',
    'midheaven': 'Midheaven',
    // Bodies
    'sun': 'Sun',
    'moon': 'Moon',
    'mercury': 'Mercury',
    'venus': 'Venus',
    'mars': 'Mars',
    'jupiter': 'Jupiter',
    'saturn': 'Saturn',
    'uranus': 'Uranus',
    'neptune': 'Neptune',
    'pluto': 'Pluto',
    'chiron': 'Chiron',
    'sirius': 'Sirius',
    // Points
    'northnode': 'North Node',
    'southnode': 'South Node',
    'lilith': 'Lilith',
    // Signs
    'aries': 'Aries',
    'taurus': 'Taurus',
    'gemini': 'Gemini',
    'cancer': 'Cancer',
    'leo': 'Leo',
    'virgo': 'Virgo',
    'libra': 'Libra',
    'scorpio': 'Scorpio',
    'sagittarius': 'Sagittarius',
    'capricorn': 'Capricorn',
    'aquarius': 'Aquarius',
    'pisces': 'Pisces',
    'ophiuchus': 'Ophiuchus',
    // Houses
    'house1': 'First',
    'house2': 'Second',
    'house3': 'Third',
    'house4': 'Fourth',
    'house5': 'Fifth',
    'house6': 'Sixth',
    'house7': 'Seventh',
    'house8': 'Eigth',
    'house9': 'Ninth',
    'house10': 'Tenth',
    'house11': 'Eleventh',
    'house12': 'Twelfth',
    // Aspects
    'conjunction': 'Conjunction',
    'opposition': 'Opposition',
    'trine': 'Trine',
    'square': 'Square',
    'sextile': 'Sextile',
    'quincunx': 'Quincunx',
    'quintile': 'Quintile',
    'septile': 'Septile',
    'semi-square': 'Semi-Square',
    'semi-sextile': 'Semi-Sextile',
    // Language labels
    'english-language': 'English',
    // Zodiac Choice Labels
    'tropical-zodiac': 'Tropical',
    'sidereal-zodiac': 'Sidereal',
    // House System labels
    'equal-house': 'Equal House',
    'koch': 'Koch',
    'placidus': 'Placidus',
    'regiomontanus': 'Regiomontanus',
    'topocentric': 'Topocentric',
    'whole-sign': 'Whole Sign',
    //Aspect level labels
    'major': 'Major',
    'minor': 'Minor',
  }
}
